name: Benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: node:17

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: actions/setup-python@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '17'
    - uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - uses: actions/setup-ruby@v1
    - uses: aminya/setup-cpp@v1
 
    - run: sh ./benchmark.sh
